name: Tests & SonarCloud
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: npm install
      
      - name: Run tests with coverage
        run: npm test
        env:
          CI: true
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Belato-code_frontend-project-46
            -Dsonar.organization=belato-code
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
